### PR TITLE
fix: Make onPlaceBlock event returning block face

### PR DESCRIPTION
**Pull request by VinkyV**
## What does this PR do?
Make onPlaceBlock event returning block face and edit docs for this event

## Which issues does this PR resolve?
None

### CODE REVIEW

**Comment by ShrBox** [comment]
https://github.com/LiteLDev/LegacyScriptEngine/commit/9c81c2dc8947cb7ada0029b19eb22bf973dbc0c8
LegacyScriptEngine's main task is keep the compability of old LLSE plugins

**Comment by VinkyV** [comment]
Could I add a new updated event?

**Comment by ShrBox** [comment]
> Could I add a new updated event? Same functionality with different name maybe

I have merged this pr, but fix truePos pre calculating.
If you need the original BlockPos, just calculating it.

**Comment by VinkyV** [comment]
Oh, okay, I just misunderstood.

**Pull request closed without merging**
